version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t jockbot_mlb .
      - run: docker run --name jockbot jockbot_mlb

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
